version: "3.8"
services:
  api:
    stdin_open: true
    build:
      context: .
    ports: 
      - "5000:3000"
    volumes:
      - "/app/node_modules"
      - "./:/app"
    env_file:
      - .env
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
networks:
  default:
    external:
      name: fe-manage-users_main
